/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicParseReceiptRouteImport } from './routes/api/public/parse-receipt'
import { Route as ApiPublicParseEmailRouteImport } from './routes/api/public/parse-email'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicParseReceiptRoute = ApiPublicParseReceiptRouteImport.update({
  id: '/api/public/parse-receipt',
  path: '/api/public/parse-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicParseEmailRoute = ApiPublicParseEmailRouteImport.update({
  id: '/api/public/parse-email',
  path: '/api/public/parse-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/parse-email': typeof ApiPublicParseEmailRoute
  '/api/public/parse-receipt': typeof ApiPublicParseReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/parse-email': typeof ApiPublicParseEmailRoute
  '/api/public/parse-receipt': typeof ApiPublicParseReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/parse-email': typeof ApiPublicParseEmailRoute
  '/api/public/parse-receipt': typeof ApiPublicParseReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/parse-email' | '/api/public/parse-receipt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/parse-email' | '/api/public/parse-receipt'
  id: '__root__' | '/' | '/api/public/parse-email' | '/api/public/parse-receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicParseEmailRoute: typeof ApiPublicParseEmailRoute
  ApiPublicParseReceiptRoute: typeof ApiPublicParseReceiptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/parse-receipt': {
      id: '/api/public/parse-receipt'
      path: '/api/public/parse-receipt'
      fullPath: '/api/public/parse-receipt'
      preLoaderRoute: typeof ApiPublicParseReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/parse-email': {
      id: '/api/public/parse-email'
      path: '/api/public/parse-email'
      fullPath: '/api/public/parse-email'
      preLoaderRoute: typeof ApiPublicParseEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicParseEmailRoute: ApiPublicParseEmailRoute,
  ApiPublicParseReceiptRoute: ApiPublicParseReceiptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
